In [10]:
## 1. Math
# (1). Random Number
import numpy as np
import random
np.random.seed(42) # Set numpy random seed
random.seed(42) # Remember to set random seed if random package is used !!
rand = np.random.rand(2,2) # Random numpy array between 0-1
randn = np.random.randn(2,2) # Random numpy array obey (0,1) normal distribution
randint = np.random.randint(((1,2),(3,4),(5,10))) # Random int numpy array between 0-Givennumber
print("rand:",rand,"randn:",randn,"randint:",randint)
# (2). Round
import math
ceil = math.ceil(1.2) # roundup
print('ceil:',ceil)
ceil = math.ceil(-1.2)
print('ceil:',ceil)
flr = math.floor(1.2) # rounddown
print('floor:',flr)
flr = math.floor(-1.2)
print('floor:',flr)

rand: [[0.37454012 0.95071431]
 [0.73199394 0.59865848]] randn: [[-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]] randint: [[0 1]
 [0 1]
 [3 5]]
ceil: 2
ceil: -1
floor: 1
floor: -2


In [ ]:
## 2. Os package
import os
dir_path = '/home/lsy/Public/02-Local Project/00-Project_ApeNote/00-Tempdata' # Python uses / as address separator
# (1). Make directory 
if not os.path.exists(dir_path):
    os.makedirs(dir_path) # An empty directory is made
# (2). Get file list
dir_path = '/home/lsy/Public/02-Local Project/'
file_list = os.listdir(dir_path) # 1d-List, Only file names !!
print("file_list:",file_list)

In [7]:
## 3._
import numpy as np
# (1) Zero np.array
zeros = np.zeros((2,4),dtype=np.int) 
# (2) List & np.array
list2np = np.array([[1,2,3],[3,2,1],[4,5,7]])
print("list2np:\n",list2np)
np2list = list(list2np)
print("npt2list:\n",np2list)
# (4) Sort np.array
sortnp = np.sort(list2np,axis=0) # Sort is not useful for 2 or more D np.array !! Pandas are especially good for this situation.
print("sortnp:\n",sortnp)
# (5) Concatenate np.array
np1 = np.zeros((21,15,2))
np2 = np.zeros((30,15,2))
npconcatenate = np.concatenate((np1,np2),axis=0)
print("npconcatenate shape:",npconcatenate.shape)
# (6) NAN np
NANnp = np.nan # Infinitesimal
print("NANnp:",NANnp)
# (7) Slicing np.array attention
slnp = np.array([0,1,2,3,4,5,6,7,8,9])
sldnp = slnp[:4] # 0,1,2,3 口诀：选取从0开始的np序号，不要记什么前后开闭界
print("sldnp:",sldnp)
sldnp = slnp[1:4] 
print("sldnp:",sldnp)
sldnp = slnp[3:-1] # 倒数第一个再减一个
print("sldnp:",sldnp)

list2np:
 [[1 2 3]
 [3 2 1]
 [4 5 7]]
npt2list:
 [array([1, 2, 3]), array([3, 2, 1]), array([4, 5, 7])]
sortnp:
 [[1 2 1]
 [3 2 3]
 [4 5 7]]
npconcatenate shape: (51, 15, 2)
NANnp: nan
sldnp: [0 1 2 3]
sldnp: [1 2 3]
sldnp: [3 4 5 6 7 8]


In [ ]:
## 4. _
import numpy as np
# (1) Numpy & txt
file = '/home/lsy/Public/02-Local Project/00-Project_ApeNote/00-Tempdata/'
name = '0401.txt'
np.savetxt(file + name,np.random.rand(3,10)) # Only 1D and 2D array available
txtdata = np.loadtxt(file + name,dtype = np.float64)
print("txtdata:",txtdata)
# (2) Numpy & npy
name = '0402.npy'
np.save(file + name, np.random.rand(3,10))
npydata = np.load(file + name)
print("npydata:",npydata)

In [ ]:
## 5. Pandas
import pandas as pd
import numpy as np
# (1). Numpy & Pandas dataframe
np.random.seed(42)
df = pd.DataFrame(np.random.rand(3,6)) # roltitle and coltitle is added by default
df2np = np.array(df) # roltitle and coltitle is ignored
print('df:\n',df)
print('df2np:\n',np)
# (2). Select the specified row, column and elements. Attention: xx = df[xx,xx] is not available !!
sdf = df.iloc[:,[0,1,2,3]]
print('sdf:\n',sdf)
sdf = df.iloc[:,:4]
print('sdf:\n',sdf)
# (3). Title df
sdf.columns = ['veh_id', 'frame_id', 'x', 'y']
print('sdf:\n',sdf)
# (4). Select element by title.
veh_id = sdf['veh_id'] # Selected pd.frames are still pd.series
print('veh_id:\n',veh_id)
# (5). Sort df
sdf = sdf.sort_values(by='veh_id') # Don't only use sdf.sort_values()
print('sdf:\n',sdf)
# (6). Unique
veh_id = pd.unique(sdf['veh_id'])
print('veh_id:\n',veh_id)
# (7). Find specific data
veh = sdf[sdf['veh_id'] == sdf.iloc[0,0]]
print('veh:\n',veh)
# (8). Construct iterator
for i,veh in sdf.iterrows():
    print('veh:',i,veh)

In [ ]:
## 6. Progress bar
import numpy as np
# (1). Simple bar
task = np.zeros(10000)
itercount = 0
for i in task:
    if itercount % 1000 == 1:
        print('Processing:', itercount / len(task)) 

In [ ]:
## 7. Collect data in loop !!
import numpy as np
np.random.seed(42)
# (1) Using Nested list then convert to np.array !!
# 口诀：先append后stack
nlist = []
for i in range(3):
    nlist.append(np.random.rand(3))
nlist2np = np.stack(nlist)
print('nlist2np:',nlist2np)
# (2) Using Dictionary to map one list to another !!
trg_dict = {}
timestamp = np.random.rand(10)
print('timestamp:',timestamp)
time_vehid = np.random.rand(10,3) # Dimension1: t Dimension2: vehicleID
for i in range(len(time_vehid)):
    trg_dict[timestamp[i]] = time_vehid[i,:] 
print('trg_dict:',trg_dict) # We can use time stamp to access vehicleID when mapping is set
# (3) Accquire keys
timestamp_copy = list(trg_dict.keys())
print('timestamp_copy:',timestamp_copy)

In [ ]:
## 8. Set & operation to filter out absent vehicles (DoNotRunThisCell)
vehs_start = list(rec_dict[start_frame].keys()) # vehicles in start frame
vehs_end = list(rec_dict[end_frame].keys()) # vehicles in end frame
if padding:
    vehs_filt = vehs_start
    for frame in range(start_frame, mid_frame + 1, 2):
        vehs_filt = list(set(vehs_filt) & set(rec_dict[frame].keys())) # set operation
else:
    vehs_filt = list(set(vehs_start) & set(vehs_end)) # set operation
# Cite from Qifan Xue, unidata d2u

In [ ]:
## 9. Different ways to set parameters for Neural-Networks (DoNotRunThisCell)
# (1). Simple way using dictionary
params = {}
params['hist_len'] = 15
params['hist_len'] = 25
params['use_lane'] = 0
params['lane_index'] = 7
params['enc_size'] = 64
params['type_map'] = 1
class UniDataset:
    def __init__(self, folder, params):
        self.dir = folder # unidata location
        self.hist_len = params['hist_len'] # history trajectory length
        self.fut_len = params['fut_len'] # future trajectory length
        self.lane = params['use_lane'] # is lane available
        
        if self.lane:
            self.lane_index = params['lane_index'] # lane index
        self.enc_size = params['enc_size'] # size of lstm encoder
        
        self.data_list = os.listdir(self.dir) # unidata list
        self.params = params
        
        if self.params.get('type_map'): # is map available
            self.type_map = params['type_map'] # map
        else:
            self.type_map = None

In [ ]:
## 10. Innovative use of dictionary
# (1). dict.get('key') to judge if an element exist
if dict.get('key'):
    self.key = params['key']
else:
    self.key = None

In [ ]:
## 11. Grid positioning algorithm (DoNotRunThisCell)
grid = np.zeros([num, self.grid[0], self.grid[1]])-1
for i in range(num): # construct nbrs grid matrix for vehicle i
    x_i = hist[i, -1, 0]
    y_i = hist[i, -1, 1]
    for j in range(num): 
        if j == i: # skip current vehicle
            continue
        x_j = hist[j, -1, 0]
        y_j = hist[j, -1, 1]
        # Grid positioning
        g_x = (x_j - x_i) / self.limit
        g_y = (y_j - y_i) / self.limit
        # X axis positioning
        if g_x > 0 and g_x < (self.grid[0] - 1)/2:
            g_x = math.ceil(g_x) + (self.grid[0] - 1)/2
        elif g_x < 0 and abs(g_x) < (self.grid[0] - 1)/2:
            g_x = math.floor(g_x) + (self.grid[0] - 1)/2
        else:
            continue
        # Y axis positioning
        if g_y > 0 and g_y < (self.grid[1] - 1)/2:
            g_y = math.ceil(g_y) + (self.grid[1] - 1)/2
        elif g_y < 0 and abs(g_y) < (self.grid[1] - 1)/2:
            g_y = math.floor(g_y) + (self.grid[1] - 1)/2
        else:
            continue
        grid[i, int(g_x), int(g_y)] = j
